# Generated by Django 3.2.4 on 2021-07-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210629_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='id',
            new_name='project_id',
        ),
    ]
